# fly.toml file generated for protohackers-vgrigoriu on 2022-12-22T11:43:37+02:00

app = "protohackers-vgrigoriu"

[[services]]
  internal_port = 2000
  protocol = "tcp"

  [[services.ports]]
    port = 2000

[[services]]
  internal_port = 2001
  protocol = "tcp"

  [[services.ports]]
    port = 2001

[[services]]
  internal_port = 2002
  protocol = "tcp"

[[services.ports]]
  port = 2002

[[services]]
  internal_port = 2003
  protocol = "tcp"

[[services.ports]]
  port = 2003
